export const pasarData = [
  {
    id: 1,
    nama: "Pasar Bogor",
    lokasi: "Jalan Suryakencana 18216",
    kota: "Bogor",
    gambar:
      "https://static.republika.co.id/uploads/images/inpicture_slide/036481400-1688106898-830-556.jpg",
    JamOperasional: "07:00 - 11:00",
    GoogleMaps: "asdisadidsi",
    tipe: "pasar",
  },
  {
    id: 2,
    nama: "Pasar Anyar",
    lokasi: "Jalan Dewi Sartika No. 10",
    kota: "Bogor",
    gambar: "https://awsimages.detik.net.id/community/media/visual/2016/02/26/1bd5fa0f-41b0-4f7a-ad3e-0aa6d6aade8b.jpg?w=700&q=90",
    JamOperasional: "06:00 - 12:00",
    GoogleMaps: "link_google_maps_pasar_anyar",
    tipe: "pasar",
  },
  {
    id: 3,
    nama: "Pasar Ciawi",
    lokasi: "Jalan Raya Ciawi No. 15",
    kota: "Bogor",
    gambar: "https://static.republika.co.id/uploads/images/inpicture_slide/pasar-tambun-bekasi-_130210201952-878.jpg",
    JamOperasional: "05:30 - 13:00",
    GoogleMaps: "link_google_maps_pasar_ciawi",
    tipe: "pasar",
  },
  {
    id: 4,
    nama: "Pasar Kebon Kembang",
    lokasi: "Jalan Merdeka No. 45",
    kota: "Bogor",
    gambar: "https://static.promediateknologi.id/crop/0x0:0x0/0x0/webp/photo/p2/115/2023/08/03/pasar-kebon-kembang-739977445.jpg",
    JamOperasional: "06:00 - 14:00",
    GoogleMaps: "link_google_maps_pasar_kebon_kembang",
    tipe: "pasar",
  },
  {
    id: 5,
    nama: "Pasar Cibinong",
    lokasi: "Jalan Raya Cibinong No. 20",
    kota: "Bogor",
    gambar: "https://assets-a1.kompasiana.com/items/album/2016/03/22/img-1389-jpg-56f09850709773b405c6b669.jpg",
    JamOperasional: "05:00 - 13:00",
    GoogleMaps: "link_google_maps_pasar_cibinong",
    tipe: "pasar",
  },
  {
    id: 6,
    nama: "Pasar Gunung Batu",
    lokasi: "Jalan Gunung Batu No. 7",
    kota: "Bogor",
    gambar: "https://assets.promediateknologi.id/crop/0x0:0x0/750x500/webp/photo/metropolitan/2019/11/IMG-20191120-WA0026.jpg",
    JamOperasional: "06:30 - 12:30",
    GoogleMaps: "link_google_maps_pasar_gunung_batu",
    tipe: "pasar",
  },
  {
    id: 7,
    nama: "Pasar Jambu Dua",
    lokasi: "Jalan Pajajaran No. 100",
    kota: "Bogor",
    gambar: "https://awsimages.detik.net.id/community/media/visual/2024/10/17/pasar-jambu-dua-dok-istimewa_169.jpeg?w=1200",
    JamOperasional: "07:00 - 11:30",
    GoogleMaps: "link_google_maps_pasar_jambu_dua",
    tipe: "pasar",
  },
  {
    id: 8,
    nama: "Pasar Sukasari",
    lokasi: "Jalan Siliwangi No.35",
    kota: "Bogor",
    gambar: "https://cloud.jpnn.com/photo/jatim/news/normal/2024/07/10/rancangan-pasar-gembrong-sukasari-kota-bogor-yang-dicanangka-gxia.jpg",
    JamOperasional: "05:30 - 12:00",
    GoogleMaps: "link_google_maps_pasar_sindangbarang",
    tipe: "pasar",
  },
  {
    id: 9,
    nama: "Pasar Sindangbarang",
    lokasi: "Jalan Sindangbarang No. 25",
    kota: "Bogor",
    gambar: "https://example.com/pasar-sindangbarang.jpg",
    JamOperasional: "05:30 - 12:00",
    GoogleMaps: "link_google_maps_pasar_sindangbarang",
    tipe: "pasar",
  },
];
